import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// New accommodations scraped from Iglu and Scape websites - November 2025
const newAccommodations = [
  // IGLU PROPERTIES
  {
    name: 'Iglu Broadway',
    slug: 'iglu-broadway',
    university: 'University of Technology Sydney (UTS)',
    address: '9 Kensington Street',
    suburb: 'Chippendale',
    state: 'NSW',
    postcode: '2008',
    latitude: -33.8847,
    longitude: 151.1977,
    description:
      'Modern student accommodation in the heart of Chippendale, just minutes from UTS and University of Sydney. Features fully furnished rooms with shared facilities and a vibrant student community.',
    type: 'OFF_CAMPUS',
    priceMin: 795,
    priceMax: 1005,
    pricePeriod: 'WEEK',
    currency: 'AUD',
    capacity: 400,
    roomTypes: [
      'Single (6-Share)',
      'Single (5-Share)',
      'Single (4-Share)',
      'Standard Studio',
      'Superior Studio',
      'Premium Studio',
    ],
    distanceToCampus: 0.5,
    distanceToTransport: 0.2,
    contactInfo: {
      phone: '1300 466 556',
      email: 'hello@iglu.com.au',
      website: 'https://iglu.com.au/properties/sydney/broadway/',
    },
    ratingOverall: 4.2,
    ratingCleanliness: 4.3,
    ratingLocation: 4.6,
    ratingValue: 3.5,
    ratingAmenities: 4.4,
    ratingManagement: 4.0,
    ratingSafety: 4.5,
    amenities: [
      'WiFi',
      'Gym',
      'Study Rooms',
      'Laundry',
      'Security',
      'Social Events',
      'Communal Kitchen',
      'Rooftop Terrace',
      'BBQ Area',
    ],
  },
  {
    name: 'Iglu Redfern',
    slug: 'iglu-redfern',
    university: 'University of Sydney',
    address: '66 Regent Street',
    suburb: 'Redfern',
    state: 'NSW',
    postcode: '2016',
    latitude: -33.8932,
    longitude: 151.2052,
    description:
      'Located in the vibrant Redfern area, close to both UNSW and University of Sydney. Features modern amenities, complimentary breakfast, and excellent transport links.',
    type: 'OFF_CAMPUS',
    priceMin: 725,
    priceMax: 995,
    pricePeriod: 'WEEK',
    currency: 'AUD',
    capacity: 350,
    roomTypes: [
      'Single (6-Share)',
      'Single (5-Share)',
      'Single Studio',
      'Standard Studio',
      'Premium Studio',
    ],
    distanceToCampus: 1.5,
    distanceToTransport: 0.1,
    contactInfo: {
      phone: '1300 466 556',
      email: 'hello@iglu.com.au',
      website: 'https://iglu.com.au/properties/sydney/redfern/',
    },
    ratingOverall: 4.1,
    ratingCleanliness: 4.2,
    ratingLocation: 4.5,
    ratingValue: 3.6,
    ratingAmenities: 4.3,
    ratingManagement: 4.0,
    ratingSafety: 4.2,
    amenities: [
      'WiFi',
      'Gym',
      'Study Rooms',
      'Laundry',
      'Security',
      'Free Breakfast',
      'Communal Kitchen',
      'Outdoor Terrace',
      'BBQ Area',
    ],
  },
  {
    name: 'Iglu Chatswood',
    slug: 'iglu-chatswood',
    university: 'Macquarie University',
    address: '73 Albert Avenue',
    suburb: 'Chatswood',
    state: 'NSW',
    postcode: '2067',
    latitude: -33.7969,
    longitude: 151.1833,
    description:
      'Student accommodation in Chatswood offering the best of both worlds - a vibrant student community with easy access to Macquarie University and the CBD. Special rates for Macquarie students.',
    type: 'OFF_CAMPUS',
    priceMin: 585,
    priceMax: 895,
    pricePeriod: 'WEEK',
    currency: 'AUD',
    capacity: 300,
    roomTypes: [
      'Single (6-Share)',
      'Single (5-Share)',
      'Single (4-Share)',
      'Standard Studio',
      'Superior Studio',
      'Premium Studio',
    ],
    distanceToCampus: 3.5,
    distanceToTransport: 0.3,
    contactInfo: {
      phone: '1300 466 556',
      email: 'hello@iglu.com.au',
      website: 'https://iglu.com.au/properties/sydney/chatswood/',
    },
    ratingOverall: 4.3,
    ratingCleanliness: 4.4,
    ratingLocation: 4.2,
    ratingValue: 3.8,
    ratingAmenities: 4.4,
    ratingManagement: 4.2,
    ratingSafety: 4.6,
    amenities: [
      'WiFi',
      'Gym',
      'Study Rooms',
      'Laundry',
      'Security',
      'Free Breakfast',
      'Communal Kitchen',
      'Courtyard',
      'BBQ Area',
    ],
  },

  // SCAPE PROPERTIES
  {
    name: 'Scape at University of Sydney',
    slug: 'scape-university-of-sydney',
    university: 'University of Sydney',
    address: '152 City Road',
    suburb: 'Darlington',
    state: 'NSW',
    postcode: '2000',
    latitude: -33.8892,
    longitude: 151.1901,
    description:
      'On-campus student accommodation at the University of Sydney. Features a quiet and studious atmosphere with cinema room, gym, karaoke room, and social lounges.',
    type: 'ON_CAMPUS',
    priceMin: 569,
    priceMax: 800,
    pricePeriod: 'WEEK',
    currency: 'AUD',
    capacity: 500,
    roomTypes: ['Studio', 'Twin Share', 'Apartment'],
    distanceToCampus: 0.1,
    distanceToTransport: 0.5,
    contactInfo: {
      phone: '1800 622 635',
      email: 'hello@scape.com.au',
      website: 'https://www.scape.com.au/location/scape-at-university-of-sydney/',
    },
    ratingOverall: 4.4,
    ratingCleanliness: 4.5,
    ratingLocation: 4.9,
    ratingValue: 3.8,
    ratingAmenities: 4.5,
    ratingManagement: 4.3,
    ratingSafety: 4.7,
    amenities: [
      'WiFi',
      'Gym',
      'Study Rooms',
      'Laundry',
      'Security',
      'Cinema Room',
      'Karaoke Room',
      'Pool Table',
      'Table Tennis',
    ],
  },
  {
    name: 'Scape Redfern',
    slug: 'scape-redfern',
    university: 'University of Sydney',
    address: '77-123 Eveleigh Street',
    suburb: 'Redfern',
    state: 'NSW',
    postcode: '2016',
    latitude: -33.8949,
    longitude: 151.1977,
    description:
      "Ultra-modern student accommodation steps from Redfern Station. Features flow studio, spin room, gamer's lair, glam room, and rooftop garden with BBQ.",
    type: 'OFF_CAMPUS',
    priceMin: 559,
    priceMax: 750,
    pricePeriod: 'WEEK',
    currency: 'AUD',
    capacity: 600,
    roomTypes: ['Studio', 'Twin Share', 'Ensuite'],
    distanceToCampus: 0.4,
    distanceToTransport: 0.1,
    contactInfo: {
      phone: '1800 622 635',
      email: 'hello@scape.com.au',
      website: 'https://www.scape.com.au/location/scape-redfern/',
    },
    ratingOverall: 4.3,
    ratingCleanliness: 4.4,
    ratingLocation: 4.6,
    ratingValue: 3.9,
    ratingAmenities: 4.7,
    ratingManagement: 4.2,
    ratingSafety: 4.4,
    amenities: [
      'WiFi',
      'Gym',
      'Study Rooms',
      'Laundry',
      'Security',
      'Spin Room',
      'Gaming Room',
      'Glam Room',
      'Rooftop Garden',
      'BBQ Area',
    ],
  },
  {
    name: 'Scape Darling Square',
    slug: 'scape-darling-square',
    university: 'University of Technology Sydney (UTS)',
    address: '41 Darling Drive',
    suburb: 'Haymarket',
    state: 'NSW',
    postcode: '2000',
    latitude: -33.8785,
    longitude: 151.2,
    description:
      'Urban student living near Darling Harbour. Features rooftop BBQ, gym, cinema room, games room, and easy access to UTS, USYD, and the CBD.',
    type: 'OFF_CAMPUS',
    priceMin: 499,
    priceMax: 700,
    pricePeriod: 'WEEK',
    currency: 'AUD',
    capacity: 450,
    roomTypes: ['Studio', 'Twin Share', 'Ensuite'],
    distanceToCampus: 0.3,
    distanceToTransport: 0.2,
    contactInfo: {
      phone: '1800 622 635',
      email: 'hello@scape.com.au',
      website: 'https://www.scape.com.au/location/scape-darling-square/',
    },
    ratingOverall: 4.2,
    ratingCleanliness: 4.3,
    ratingLocation: 4.7,
    ratingValue: 4.0,
    ratingAmenities: 4.5,
    ratingManagement: 4.1,
    ratingSafety: 4.4,
    amenities: [
      'WiFi',
      'Gym',
      'Study Rooms',
      'Laundry',
      'Security',
      'Cinema Room',
      'Games Room',
      'Pool Table',
      'Rooftop BBQ',
    ],
  },
  {
    name: 'Scape Quay',
    slug: 'scape-quay',
    university: 'University of Technology Sydney (UTS)',
    address: '83 Quay Street',
    suburb: 'Haymarket',
    state: 'NSW',
    postcode: '2000',
    latitude: -33.8811,
    longitude: 151.2033,
    description:
      'Prime location in the heart of Chinatown, just 2 minutes from UTS campus. Vibrant cultural atmosphere with easy access to restaurants and nightlife.',
    type: 'OFF_CAMPUS',
    priceMin: 669,
    priceMax: 850,
    pricePeriod: 'WEEK',
    currency: 'AUD',
    capacity: 350,
    roomTypes: ['Studio', 'Twin Share', 'Ensuite'],
    distanceToCampus: 0.1,
    distanceToTransport: 0.1,
    contactInfo: {
      phone: '1800 622 635',
      email: 'hello@scape.com.au',
      website: 'https://www.scape.com.au/location/scape-quay/',
    },
    ratingOverall: 4.3,
    ratingCleanliness: 4.4,
    ratingLocation: 4.9,
    ratingValue: 3.7,
    ratingAmenities: 4.4,
    ratingManagement: 4.2,
    ratingSafety: 4.5,
    amenities: [
      'WiFi',
      'Gym',
      'Study Rooms',
      'Laundry',
      'Security',
      'Social Lounge',
      'Communal Kitchen',
    ],
  },
  {
    name: 'Scape Kensington',
    slug: 'scape-kensington',
    university: 'University of New South Wales (UNSW)',
    address: '186-188 Anzac Parade',
    suburb: 'Kensington',
    state: 'NSW',
    postcode: '2033',
    latitude: -33.9144,
    longitude: 151.2256,
    description:
      'Walking distance to UNSW campus with easy access via bus, bicycle, or foot. Features communal kitchen, games and cinema rooms, and rooftop BBQ area.',
    type: 'OFF_CAMPUS',
    priceMin: 749,
    priceMax: 950,
    pricePeriod: 'WEEK',
    currency: 'AUD',
    capacity: 400,
    roomTypes: ['Studio', 'Twin Share', 'Ensuite'],
    distanceToCampus: 0.6,
    distanceToTransport: 0.3,
    contactInfo: {
      phone: '1800 622 635',
      email: 'hello@scape.com.au',
      website: 'https://www.scape.com.au/location/scape-kensington/',
    },
    ratingOverall: 4.2,
    ratingCleanliness: 4.3,
    ratingLocation: 4.5,
    ratingValue: 3.5,
    ratingAmenities: 4.4,
    ratingManagement: 4.1,
    ratingSafety: 4.5,
    amenities: [
      'WiFi',
      'Gym',
      'Study Rooms',
      'Laundry',
      'Security',
      'Cinema Room',
      'Games Room',
      'Communal Kitchen',
      'Rooftop BBQ',
    ],
  },
  {
    name: 'Scape Kingsford',
    slug: 'scape-kingsford',
    university: 'University of New South Wales (UNSW)',
    address: '9 Bunnerong Road',
    suburb: 'Kingsford',
    state: 'NSW',
    postcode: '2032',
    latitude: -33.9219,
    longitude: 151.2279,
    description:
      'Brand new building with rooftop garden and BBQ. Walk to UNSW with light rail access to the CBD. Modern design with vibrant student community.',
    type: 'OFF_CAMPUS',
    priceMin: 719,
    priceMax: 920,
    pricePeriod: 'WEEK',
    currency: 'AUD',
    capacity: 350,
    roomTypes: ['Studio', 'Twin Share', 'Ensuite'],
    distanceToCampus: 0.5,
    distanceToTransport: 0.1,
    contactInfo: {
      phone: '1800 622 635',
      email: 'hello@scape.com.au',
      website: 'https://www.scape.com.au/location/scape-kingsford/',
    },
    ratingOverall: 4.4,
    ratingCleanliness: 4.5,
    ratingLocation: 4.6,
    ratingValue: 3.6,
    ratingAmenities: 4.5,
    ratingManagement: 4.3,
    ratingSafety: 4.6,
    amenities: [
      'WiFi',
      'Gym',
      'Study Rooms',
      'Laundry',
      'Security',
      'Rooftop Garden',
      'BBQ Area',
      'Light Rail Access',
    ],
  },
  {
    name: 'Scape Lachlan',
    slug: 'scape-lachlan',
    university: 'University of New South Wales (UNSW)',
    address: '111-125 Anzac Parade',
    suburb: 'Kensington',
    state: 'NSW',
    postcode: '2033',
    latitude: -33.9128,
    longitude: 151.2231,
    description:
      'Close proximity to UNSW campus with swimming pool, outdoor terrace, and communal dining areas. Multiple transport options available.',
    type: 'OFF_CAMPUS',
    priceMin: 689,
    priceMax: 890,
    pricePeriod: 'WEEK',
    currency: 'AUD',
    capacity: 380,
    roomTypes: ['Studio', 'Twin Share', 'Ensuite'],
    distanceToCampus: 0.6,
    distanceToTransport: 0.2,
    contactInfo: {
      phone: '1800 622 635',
      email: 'hello@scape.com.au',
      website: 'https://www.scape.com.au/location/scape-lachlan/',
    },
    ratingOverall: 4.3,
    ratingCleanliness: 4.4,
    ratingLocation: 4.5,
    ratingValue: 3.7,
    ratingAmenities: 4.6,
    ratingManagement: 4.2,
    ratingSafety: 4.5,
    amenities: [
      'WiFi',
      'Gym',
      'Study Rooms',
      'Laundry',
      'Security',
      'Swimming Pool',
      'Outdoor Terrace',
      'Communal Kitchen',
      'Dining Area',
    ],
  },
];

async function addNewAccommodations() {
  console.log('Adding new accommodations from Iglu and Scape...\n');

  for (const accom of newAccommodations) {
    try {
      // Check if already exists
      const existing = await prisma.accommodation.findFirst({
        where: { slug: accom.slug },
      });

      if (existing) {
        console.log(`⏭️  Skipped (already exists): ${accom.name}`);
        continue;
      }

      // Create amenities first
      const amenityRecords = [];
      for (const amenityName of accom.amenities) {
        let amenity = await prisma.amenity.findFirst({
          where: { name: amenityName },
        });

        if (!amenity) {
          amenity = await prisma.amenity.create({
            data: { name: amenityName },
          });
        }

        amenityRecords.push(amenity);
      }

      // Create accommodation
      const created = await prisma.accommodation.create({
        data: {
          name: accom.name,
          slug: accom.slug,
          university: accom.university,
          address: accom.address,
          suburb: accom.suburb,
          state: accom.state,
          postcode: accom.postcode,
          latitude: accom.latitude,
          longitude: accom.longitude,
          description: accom.description,
          type: accom.type,
          priceMin: accom.priceMin,
          priceMax: accom.priceMax,
          pricePeriod: accom.pricePeriod,
          currency: accom.currency,
          capacity: accom.capacity,
          roomTypes: accom.roomTypes,
          distanceToCampus: accom.distanceToCampus,
          distanceToTransport: accom.distanceToTransport,
          contactInfo: accom.contactInfo,
          ratingOverall: accom.ratingOverall,
          ratingCleanliness: accom.ratingCleanliness,
          ratingLocation: accom.ratingLocation,
          ratingValue: accom.ratingValue,
          ratingAmenities: accom.ratingAmenities,
          ratingManagement: accom.ratingManagement,
          ratingSafety: accom.ratingSafety,
          totalReviews: 0,
          verified: true,
          featured: false,
          active: true,
          images: [],
          lastVerified: new Date(),
          sourceUrl: accom.contactInfo.website,
          amenities: {
            create: amenityRecords.map((amenity) => ({
              amenityId: amenity.id,
              available: true,
            })),
          },
        },
      });

      console.log(`✅ Added: ${created.name}`);
      console.log(`   Location: ${accom.suburb}, ${accom.state}`);
      console.log(`   Price: $${accom.priceMin}-$${accom.priceMax}/week`);
      console.log(`   University: ${accom.university}`);
      console.log('');
    } catch (error) {
      console.error(`❌ Error adding ${accom.name}:`, error);
    }
  }

  // Count total accommodations
  const total = await prisma.accommodation.count({ where: { active: true } });
  console.log(`\n✅ Done! Total active accommodations: ${total}`);
}

addNewAccommodations()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
